stages:
  - build
  - deploy
  - migrate

variables:
  TAG: ${CI_PIPELINE_IID}
  DOCKER_IMAGE: canban

build:
  stage: build
  script:
    - echo "$ENV" > .env
    - docker build -t $DOCKER_IMAGE:$TAG -f Dockerfile .
  only:
    - main
  tags:
    - temppriz

deploy:
  stage: deploy
  script:
    - docker compose down
    - docker volume rm canban || echo "Volume not found, skipping"
    - docker compose up -d 
  only:
    - main
  tags:
    - temppriz
  
migrate:
  stage: migrate
  script:
    - docker exec canban php artisan migrate
  when: manual
  only:
    - main
  tags:
    - temppriz

