name: canban

networks:
  app-network:
    external: true

services:
  canban:
    image: $DOCKER_IMAGE:$TAG
    container_name: canban
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - code:/var/www
      - /var/www/vhosts/canban-storage:/var/www/storage
      - /var/www/vhosts/canban-storage/app/public:/var/www/public/storage

  canban_nginx:
    image: nginx:stable-alpine
    container_name: canban_nginx
    restart: unless-stopped
    ports:
      - "99:80"
    networks:
      - app-network
    volumes:
      - code:/var/www:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /var/www/vhosts/canban-storage:/var/www/storage
      - /var/www/vhosts/canban-storage/app/public:/var/www/public/storage

volumes:
  code:
    name: canban
